# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 671)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/avatar-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 4, 1, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.layoutWidget)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.create_button = QtWidgets.QPushButton(self.layoutWidget)
        self.create_button.setMinimumSize(QtCore.QSize(0, 40))
        self.create_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout_2.addWidget(self.create_button)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.delete_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_button.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 3, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 6, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GOOD = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GOOD.setContentsMargins(0, 0, 0, 0)
        self.GOOD.setObjectName("GOOD")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 3, 1, 1, 1)
        self.launch_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.launch_button.setMinimumSize(QtCore.QSize(70, 40))
        self.launch_button.setMaximumSize(QtCore.QSize(342, 16777215))
        self.launch_button.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.launch_button.setObjectName("launch_button")
        self.gridLayout_2.addWidget(self.launch_button, 26, 1, 1, 1)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_52.setMinimumSize(QtCore.QSize(270, 0))
        self.label_52.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_52.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_52.addWidget(self.label_52)
        self.jumphost_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.jumphost_input.setMinimumSize(QtCore.QSize(150, 25))
        self.jumphost_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jumphost_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.jumphost_input.setObjectName("jumphost_input")
        self.horizontalLayout_52.addWidget(self.jumphost_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_52, 16, 0, 1, 3)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_61.setMinimumSize(QtCore.QSize(270, 0))
        self.label_61.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_61.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_61.addWidget(self.label_61)
        self.port_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.port_input.setMinimumSize(QtCore.QSize(150, 25))
        self.port_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.port_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.port_input.setObjectName("port_input")
        self.horizontalLayout_61.addWidget(self.port_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_61, 6, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 1)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.kill_other_sessions_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.kill_other_sessions_checkbox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.kill_other_sessions_checkbox.setObjectName("kill_other_sessions_checkbox")
        self.horizontalLayout_59.addWidget(self.kill_other_sessions_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_59, 10, 0, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 25, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 5, 1, 1, 1)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_62.setMinimumSize(QtCore.QSize(270, 0))
        self.label_62.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_62.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_62.addWidget(self.label_62)
        self.hostname_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hostname_input.setMinimumSize(QtCore.QSize(150, 25))
        self.hostname_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hostname_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.hostname_input.setObjectName("hostname_input")
        self.horizontalLayout_62.addWidget(self.hostname_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_62, 4, 0, 1, 3)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.forward_ssh_agent_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.forward_ssh_agent_checkbox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.forward_ssh_agent_checkbox.setObjectName("forward_ssh_agent_checkbox")
        self.horizontalLayout_50.addWidget(self.forward_ssh_agent_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_50, 20, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 23, 1, 1, 1)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.connect_osx_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.connect_osx_checkbox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.connect_osx_checkbox.setObjectName("connect_osx_checkbox")
        self.horizontalLayout_49.addWidget(self.connect_osx_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_49, 22, 0, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 27, 1, 1, 1)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_60.setMinimumSize(QtCore.QSize(270, 0))
        self.label_60.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_60.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_60.addWidget(self.label_60)
        self.username_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.username_input.setMinimumSize(QtCore.QSize(150, 25))
        self.username_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.username_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.username_input.setObjectName("username_input")
        self.horizontalLayout_60.addWidget(self.username_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_60, 8, 0, 1, 3)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 11, 1, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_53.setMinimumSize(QtCore.QSize(270, 0))
        self.label_53.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_53.setToolTip("")
        self.label_53.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_53.addWidget(self.label_53)
        self.reverse_tunnel_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.reverse_tunnel_input.setMinimumSize(QtCore.QSize(150, 25))
        self.reverse_tunnel_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reverse_tunnel_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.reverse_tunnel_input.setObjectName("reverse_tunnel_input")
        self.horizontalLayout_53.addWidget(self.reverse_tunnel_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_53, 14, 0, 1, 3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 21, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem19, 7, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(150, 50))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_8.addWidget(self.textEdit, 0, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_78.setMinimumSize(QtCore.QSize(80, 40))
        self.label_78.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_78.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(150, 20))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_8.addWidget(self.textEdit_2, 2, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_79.setMinimumSize(QtCore.QSize(80, 40))
        self.label_79.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_79.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_79.setObjectName("label_79")
        self.gridLayout_8.addWidget(self.label_79, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 24, 0, 1, 3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem20, 19, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem21, 17, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem22, 15, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem23, 9, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem24, 13, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_51.setMinimumSize(QtCore.QSize(270, 0))
        self.label_51.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_51.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_51.addWidget(self.label_51)
        self.jumphost_port = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.jumphost_port.setMinimumSize(QtCore.QSize(150, 25))
        self.jumphost_port.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jumphost_port.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.jumphost_port.setObjectName("jumphost_port")
        self.horizontalLayout_51.addWidget(self.jumphost_port)
        self.gridLayout_2.addLayout(self.horizontalLayout_51, 18, 0, 1, 3)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_54.setMinimumSize(QtCore.QSize(270, 0))
        self.label_54.setMaximumSize(QtCore.QSize(184, 16777215))
        self.label_54.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_54.addWidget(self.label_54)
        self.tunnel_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tunnel_input.setMinimumSize(QtCore.QSize(150, 25))
        self.tunnel_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tunnel_input.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.tunnel_input.setObjectName("tunnel_input")
        self.horizontalLayout_54.addWidget(self.tunnel_input)
        self.gridLayout_2.addLayout(self.horizontalLayout_54, 12, 0, 1, 3)
        self.GOOD.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.GOOD.addItem(spacerItem25, 0, 2, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.GOOD.addItem(spacerItem26, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_52.setBuddy(self.jumphost_input)
        self.label_61.setBuddy(self.port_input)
        self.label_62.setBuddy(self.hostname_input)
        self.label_60.setBuddy(self.username_input)
        self.label_53.setBuddy(self.reverse_tunnel_input)
        self.label_78.setBuddy(self.textEdit)
        self.label_79.setBuddy(self.textEdit)
        self.label_51.setBuddy(self.jumphost_port)
        self.label_54.setBuddy(self.tunnel_input)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.hostname_input, self.port_input)
        MainWindow.setTabOrder(self.port_input, self.username_input)
        MainWindow.setTabOrder(self.username_input, self.kill_other_sessions_checkbox)
        MainWindow.setTabOrder(self.kill_other_sessions_checkbox, self.tunnel_input)
        MainWindow.setTabOrder(self.tunnel_input, self.reverse_tunnel_input)
        MainWindow.setTabOrder(self.reverse_tunnel_input, self.jumphost_input)
        MainWindow.setTabOrder(self.jumphost_input, self.jumphost_port)
        MainWindow.setTabOrder(self.jumphost_port, self.forward_ssh_agent_checkbox)
        MainWindow.setTabOrder(self.forward_ssh_agent_checkbox, self.connect_osx_checkbox)
        MainWindow.setTabOrder(self.connect_osx_checkbox, self.launch_button)
        MainWindow.setTabOrder(self.launch_button, self.create_button)
        MainWindow.setTabOrder(self.create_button, self.delete_button)
        MainWindow.setTabOrder(self.delete_button, self.treeView)
        MainWindow.setTabOrder(self.treeView, self.textEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ethernal Terminal"))
        self.create_button.setText(_translate("MainWindow", "Create"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Profiles"))
        self.launch_button.setText(_translate("MainWindow", "Launch"))
        self.label_52.setToolTip(_translate("MainWindow", "A jump server, jump host or jump box is a system on a network used to access and manage devices in a separate security zone."))
        self.label_52.setText(_translate("MainWindow", "Jumphost"))
        self.label_61.setToolTip(_translate("MainWindow", "The port number where you want to connect on the specified host."))
        self.label_61.setText(_translate("MainWindow", "Port"))
        self.kill_other_sessions_checkbox.setToolTip(_translate("MainWindow", "Kill the previous sessions opened on the connected machine."))
        self.kill_other_sessions_checkbox.setText(_translate("MainWindow", "Kill other sessions on connect"))
        self.label_62.setToolTip(_translate("MainWindow", "The IP address of the remote machine where you want to connect to."))
        self.label_62.setText(_translate("MainWindow", "Hostname"))
        self.forward_ssh_agent_checkbox.setToolTip(_translate("MainWindow", "Allow external devices access to computers services on private networks."))
        self.forward_ssh_agent_checkbox.setText(_translate("MainWindow", "Forward SSH Agent"))
        self.connect_osx_checkbox.setText(_translate("MainWindow", "Connecting to OS/X Server"))
        self.label_60.setToolTip(_translate("MainWindow", "The username with which you want to connect."))
        self.label_60.setText(_translate("MainWindow", "Username"))
        self.label_53.setText(_translate("MainWindow", "Reverse Tunnel (access local servers)"))
        self.label_78.setText(_translate("MainWindow", "CMD:"))
        self.label_79.setText(_translate("MainWindow", "CMD name:"))
        self.label_2.setText(_translate("MainWindow", "Parameters"))
        self.label_51.setText(_translate("MainWindow", "Jumphost Port"))
        self.label_54.setToolTip(_translate("MainWindow", "A Secure Shell (SSH) tunnel consists of an encrypted tunnel created through an SSH protocol connection. Users may set up SSH tunnels to transfer unencrypted traffic over a network through an encrypted channel."))
        self.label_54.setText(_translate("MainWindow", "Tunnel (access servers on remote)"))

import resources_rc
